include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Tratar lints como erros no CI mantem o port limpo.
    todo: ignore

linter:
  rules:
    - prefer_final_locals
    - prefer_const_constructors
    - avoid_print
